#!/usr/bin/env python3
"""The Astrologer's look for the race and class pickers (Origins, Alternate Origin GUI, Origins: Classes).

Every race and class in the game gets its own star icon, drawn from its current icon, so the Medieval Origins,
Origins++ and Classes icons stop looking like three different mods. The icons are shown by one hidden Binder item
(mdvlcraft:origin_icon) that picks its texture by CustomModelData; modpack/origins_overrides.py points every
race and class at it (modpack/origin_icons.json holds the numbering). The picker panel, the origin list and the
power badges are recoloured into the night-sky palette, keeping their layout, in a resource pack the client
packs list above the mods' resources (modpack/client-overrides/resourcepacks/MDVLCraft-Astrologer-UI.zip).

Usage (from mdvlcraft-binder/, after modpack/origins_overrides.py has written the race list):
  python3 tools/astro_origins.py <vanilla 1.20.1 client jar>
"""
import hashlib
import io
import json
import sys
import zipfile
from pathlib import Path

from PIL import Image, ImageDraw

sys.argv = sys.argv[:2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import astro_theme as astro  # noqa: E402  (texture loading and the star icon)

BINDER = astro.BINDER
RES = astro.RES
PACK = BINDER.parent / 'modpack'
OVERRIDES = PACK / 'overrides/kubejs/data'
ORIGIN_JARS = ('origins-forge-', 'Medieval Origins Revival-', 'origins-plus-plus-', 'origins-classes-forge-')
ICON_TEX = RES / 'assets/mdvlcraft/textures/item/origin'
MODELS = RES / 'assets/mdvlcraft/models/item'
ICON_ITEM = 'mdvlcraft:origin_icon'


def jars():
    shipped = {Path(f['path']).name for f in json.load(open(PACK / 'client.modrinth.index.json'))['files']}
    return [zipfile.ZipFile(BINDER / 'libs/modpack' / n) for n in sorted(shipped)
            if n.startswith(ORIGIN_JARS) and (BINDER / 'libs/modpack' / n).exists()]


ZIPS = jars()


def data(ns, kind, path, jar_only=False):
    over = OVERRIDES / ns / kind / f'{path}.json'
    if over.exists() and not jar_only:
        return json.loads(over.read_text())
    for z in ZIPS:
        if f'data/{ns}/{kind}/{path}.json' in z.namelist():
            return json.loads(z.read(f'data/{ns}/{kind}/{path}.json'))
    raise SystemExit(f'{ns}:{kind}/{path} not found')


def asset_json(rl, kind):
    ns, path = rl.split(':', 1)
    name = f'assets/{ns}/{kind}/{path}.json'
    for z in ZIPS + [zipfile.ZipFile(j) for j in astro.JARS if j.endswith('.jar')]:
        if name in z.namelist():
            return json.loads(z.read(name))
    return None


def original_icon(icon):
    """The picture the race or class shows today (following Medieval Origins' CustomModelData models)."""
    if isinstance(icon, str):
        icon = {'item': icon}
    item = icon['item']
    if item == ICON_ITEM:
        raise SystemExit('icons were already swapped: re-run modpack/origins_overrides.py first')
    if item == 'minecraft:player_head':  # Human: the default player face
        return astro.load_texture('minecraft:textures/entity/player/wide/steve.png').crop((8, 8, 16, 16))
    cmd = None
    if 'CustomModelData:' in icon.get('tag', ''):
        cmd = int(icon['tag'].split('CustomModelData:')[1].split('}')[0])
    if cmd is not None:
        ns, path = item.split(':')
        model = asset_json(f'{ns}:item/{path}', 'models')
        for o in (model or {}).get('overrides', []):
            if o['predicate'].get('custom_model_data') == cmd:
                sub = asset_json(o['model'], 'models')
                return astro.load_texture(sub['textures']['layer0'].replace(':', ':textures/', 1) + '.png')
    animated = {'minecraft:compass': 'compass_16', 'minecraft:clock': 'clock_00'}  # items drawn from animation frames
    if item in animated:
        return astro.load_texture(f'minecraft:textures/item/{animated[item]}.png')
    return astro.source_image({'type': 'item', 'data': {'item': item}})


# Simple 16x16 silhouettes for the races, so every race icon is drawn the same way ('#' shape, '+' inner line).
RACE_GLYPHS = {
    'origins:human': """
......####......
.....######.....
.....##++##.....
.....######.....
......####......
...##########...
..############..
..##.######.##..
..##.######.##..
..##.######.##..
.....######.....
.....##..##.....
.....##..##.....
.....##..##.....
.....##..##.....
....###..###....""",
    'origins:feline': """
..#..........#..
..##........##..
..###......###..
..############..
.##############.
.##############.
.###++####++###.
.###++####++###.
.##############.
.######++######.
.#####+##+#####.
..############..
...##########...
....########....
................
................""",
    'origins:merling': """
................
................
..........##....
.........####...
#.......######..
##.....########.
###...####+#####
####.###########
####.###########
###...##########
##.....########.
#.......######..
.........####...
..........##....
................
................""",
    'medievalorigins:arachnae': """
................
.#....####....#.
..#..######..#..
...#.##++##.#...
#...########...#
.##.########.##.
...##########...
....########....
...##########...
.##.###++###.##.
#...########...#
...#.######.#...
..#...####...#..
.#............#.
................
................""",
    'medievalorigins:dwarf': """
.....######.....
....########....
....##++++##....
....########....
....#+####+#....
...##########...
..############..
..############..
..###+####+###..
...##########...
...##########...
....########....
.....######.....
......####......
.......##.......
................""",
    'medievalorigins:wood_elf': """
...........###..
.........######.
.......########.
......#########.
.....####+#####.
....####+######.
...####+######..
...###+######...
..###+######....
..##+######.....
..#+######......
.#+#####........
.#+###..........
#+..............
#...............
................""",
    'medievalorigins:goblin': """
................
#..............#
##............##
.###..####..###.
..############..
...##########...
...#++####++#...
...##########...
...####++####...
...##########...
...#+######+#...
....#++++++#....
.....######.....
................
................
................""",
    'medievalorigins:siren': """
................
................
.......##.......
......####......
.....######.....
....##+##+##....
...###+##+###...
..####+##+####..
..####+##+####..
.#####+##+#####.
.#####+##+#####.
################
################
.##############.
................
................""",
    'medievalorigins:ogre': """
..........####..
.........######.
........#######.
.......#######..
......#######...
.....#######....
....######......
...######.......
..#####.........
.####...........
.###............
####............
###.............
##..............
................
................""",
    'origins-plus-plus:land_shark': """
................
................
.......##.......
......###.......
.....####.......
....#####.......
...######.......
..#######.......
.########.......
################
################
.##############.
..############..
................
................
................""",
    'origins-plus-plus:kirin': """
......##........
.....###........
.....##.........
....###.........
....##.###......
...#########....
..###########...
..####+######...
.#############..
.##########.....
..########......
...######.......
...######.......
....#####.......
....#####.......
.....###........""",
    'origins-plus-plus:raptus': """
................
.##.........##..
.###.......###..
..###.....###...
...###...###....
....###.###.....
.....#####......
....#######.....
...#########....
..###+###+###...
..##.##.##.##...
.##..##.##..##..
.#...#...#...#..
................
................
................""",
    'origins-plus-plus:rat': """
................
.##........##...
####......####..
####......####..
.##############.
..############..
..###++##++###..
..############..
...##########...
....###++###....
.....######.....
......####......
.......##.......
................
................
................""",
    'origins-plus-plus:shadow': """
................
......#####.....
....#####.......
...####.........
..####..........
..###...........
.####...........
.####...........
.####...........
.####...........
..###...........
..####..........
...####.........
....#####.......
......#####.....
................""",
    'origins-plus-plus:sporeling': """
................
.....######.....
...##########...
..####+##+####..
.##############.
.##+########+##.
################
################
.....######.....
.....######.....
.....##++##.....
.....######.....
.....######.....
....########....
................
................""",
}


def glyph_image(art):
    rows = [r for r in art.strip('\n').split('\n')]
    im = Image.new('RGBA', (16, 16), (0, 0, 0, 0))
    for y, row in enumerate(rows[:16]):
        for x, ch in enumerate(row[:16]):
            if ch == '#':
                im.putpixel((x, y), (235, 240, 255, 255))
            elif ch == '+':
                im.putpixel((x, y), (60, 70, 110, 255))
    return im


def icons():
    races = json.loads((OVERRIDES / 'origins/origin_layers/origin.json').read_text())['origins']
    classes = data('origins-classes', 'origin_layers', 'class')['origins']
    ICON_TEX.mkdir(parents=True, exist_ok=True)
    MODELS.mkdir(parents=True, exist_ok=True)
    numbering, overrides = {}, []
    for n, oid in enumerate(races + classes, start=1):
        ns, path = oid.split(':')
        name = f"{ns.replace('-', '_')}_{path}"
        if oid in RACE_GLYPHS:  # races: a simple silhouette, the same for every race mod
            src = glyph_image(RACE_GLYPHS[oid])
        else:  # classes: drawn from the class's own item
            src = original_icon(data(ns, 'origins', path, jar_only=True)['icon'])
        kind = 'archetype' if oid in races else 'skill'  # races in starlight blue, classes in gold
        astro.pixel_icon(src, kind, f'origin/{name}', 16).save(ICON_TEX / f'{name}.png')  # item size, one pixel per GUI pixel
        (MODELS / f'origin/{name}.json').parent.mkdir(parents=True, exist_ok=True)
        (MODELS / f'origin/{name}.json').write_text(json.dumps(
            {'parent': 'minecraft:item/generated', 'textures': {'layer0': f'mdvlcraft:item/origin/{name}'}}, indent=2) + '\n')
        overrides.append({'predicate': {'custom_model_data': n}, 'model': f'mdvlcraft:item/origin/{name}'})
        numbering[oid] = n
    (MODELS / 'origin_icon.json').write_text(json.dumps(
        {'parent': 'minecraft:item/generated', 'textures': {'layer0': f"mdvlcraft:item/origin/{next(iter(numbering)).replace(':', '_').replace('-', '_')}"},
         'overrides': overrides}, indent=2) + '\n')
    (PACK / 'origin_icons.json').write_text(json.dumps(numbering, indent=2) + '\n')
    return numbering


# ------------------------------------------------------------------------------------- screen textures
NAVY = [(5, 7, 15), (8, 10, 24), (12, 15, 36), (18, 23, 52), (26, 32, 70), (40, 48, 92)]
GOLD = {(170, 126, 15): (170, 140, 80), (219, 162, 19): (224, 194, 122), (73, 54, 6): (60, 48, 26),
        (255, 255, 255): (170, 140, 80)}
TILES = {(155, 219, 149): (76, 92, 150), (47, 99, 55): (26, 32, 70)}


def sky(x, y, h, faint=False):
    """The night sky inside a panel: a soft vertical gradient with a few fixed stars (fewer and dimmer behind text)."""
    t = y / max(1, h)
    base = tuple(int(a + (b - a) * t) for a, b in zip((14, 18, 44), (8, 11, 30)))
    roll = hashlib.md5(f'{x},{y}'.encode()).digest()[0]
    if roll > 253:
        return (60, 70, 112) if faint else (196, 208, 240)
    if roll > 250 and not faint:
        return (70, 82, 128)
    return base


def recolour(im, faint=False):
    im = im.convert('RGBA')
    px = im.load()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            c = (r, g, b)
            if c == (85, 85, 85):
                c = sky(x, y, im.height, faint)
            elif c in GOLD:
                c = GOLD[c]
            elif c in TILES:
                c = TILES[c]
            elif r == g == b:  # the grey bevel ramp becomes navy
                c = NAVY[min(len(NAVY) - 1, r * len(NAVY) // 256)]
            px[x, y] = c + (a,)
    return im


def badge(src):
    """A power badge as a small astrolabe disc: navy face, rim in the badge's colour, its glyph in starlight."""
    src = src.convert('RGBA')
    w, h = src.size
    px = src.load()
    counts = {}
    for y in range(h):
        for x in range(w):
            c = px[x, y]
            if c[3] and c[:3] != (0, 0, 0):
                counts[c[:3]] = counts.get(c[:3], 0) + 1
    hue = max(counts, key=counts.get) if counts else (200, 212, 235)
    out = Image.new('RGBA', (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(out)
    d.ellipse((0, 0, w - 1, h - 1), fill=NAVY[3] + (255,), outline=hue + (255,))
    op = out.load()
    for y in range(2, h - 2):
        for x in range(2, w - 2):  # the glyph: black pixels inside the badge's border
            if px[x, y][3] and px[x, y][:3] == (0, 0, 0):
                op[x, y] = tuple(min(255, int(v * 0.35 + 170)) for v in hue) + (255,)
    return out


UI_PACK = PACK / 'client-overrides/resourcepacks/MDVLCraft-Astrologer-UI.zip'
# other mods' text that must win over the mod's own lang file (the skill trees open from the MDVLCraft menu only)
LANG = {
    'puffish_skills': {'chat.puffish_skills.new_point': 'You have a new skill point. Assign it from the Skills page of the MDVLCraft menu.'},
    'voicechat': {'message.voicechat.set_up': 'Open Voice Chat from the MDVLCraft menu to set it up'},
}


def screens():
    """The picker textures go in a small resource pack listed above the mods' own resources (a mod's copy of
    another mod's GUI texture does not reliably win inside Forge's combined mod resources)."""
    out = {
        'origins:textures/gui/choose_origin.png': recolour(astro.load_texture('origins:textures/gui/choose_origin.png'), faint=True),
        'altorigingui:textures/gui/origin_choices.png': recolour(astro.load_texture('altorigingui:textures/gui/origin_choices.png')),
    }
    for b in ('active', 'arrow_up', 'info', 'recipe', 'star', 'toggle'):
        out[f'origins:textures/gui/badge/{b}.png'] = badge(astro.load_texture(f'origins:textures/gui/badge/{b}.png'))
    UI_PACK.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(UI_PACK, 'w', zipfile.ZIP_DEFLATED) as z:
        def add(name, data):
            info = zipfile.ZipInfo(name, (2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, data)
        add('pack.mcmeta', json.dumps({'pack': {'pack_format': 15, 'description': 'MDVLCraft: the Astrologer look for the race and class pickers'}}, indent=2))
        for rl, im in sorted(out.items()):
            ns, path = rl.split(':')
            buf = io.BytesIO()
            im.save(buf, 'PNG')
            add(f'assets/{ns}/{path}', buf.getvalue())
        for ns, entries in sorted(LANG.items()):
            add(f'assets/{ns}/lang/en_us.json', json.dumps(entries, indent=2, ensure_ascii=False))
    return list(out)


if __name__ == '__main__':
    n = icons()
    s = screens()
    print(f'{len(n)} race and class icons, {len(s)} screen textures')
