"""Three candidate class names for every pair of archetypes (any two of the 17 can be picked together).
The chosen names go into the Binder's Status screen ("Class: <name>")."""
ARCHETYPES = ['knight', 'samurai', 'berzerker', 'holy', 'flame', 'lightning', 'necromancy', 'ice', 'water', 'assassin',
              'phantom', 'scout', 'thief', 'wanderer', 'stalker', 'druid', 'cursed']
NAMES = {
    ('knight', 'samurai'): ['Warlord', 'Blademaster', 'Shogun'],
    ('knight', 'berzerker'): ['Juggernaut', 'Warbringer', 'Ravager'],
    ('knight', 'holy'): ['Paladin', 'Templar', 'Crusader'],
    ('knight', 'flame'): ['Flame Warden', 'Emberknight', 'Pyre Guard'],
    ('knight', 'lightning'): ['Stormguard', 'Thunder Knight', 'Tempest Lord'],
    ('knight', 'necromancy'): ['Death Knight', 'Grave Warden', 'Dread Lord'],
    ('knight', 'ice'): ['Frost Warden', 'Rimeguard', 'Glacier Knight'],
    ('knight', 'water'): ['Tidewarden', 'Sea Sentinel', 'Coral Knight'],
    ('knight', 'assassin'): ['Blackguard', 'Shadow Knight', 'Executioner'],
    ('knight', 'phantom'): ['Spectral Knight', 'Wraithguard', 'Cavalier'],
    ('knight', 'scout'): ['Vanguard', 'Outrider', 'Lancer'],
    ('knight', 'thief'): ['Mercenary', 'Rogue Knight', 'Brigand Lord'],
    ('knight', 'wanderer'): ['Knight-Errant', 'Hedge Knight', 'Wayfarer'],
    ('knight', 'stalker'): ['Sentinel', 'Bowknight', 'Watchwarden'],
    ('knight', 'druid'): ['Grove Warden', 'Thornguard', 'Oak Knight'],
    ('knight', 'cursed'): ['Hexguard', 'Accursed Knight', 'Doom Warden'],
    ('samurai', 'berzerker'): ['Oni', 'Blood Samurai', 'Berserk Blade'],
    ('samurai', 'holy'): ['Kensei', 'Sohei', 'Shrine Guardian'],
    ('samurai', 'flame'): ['Flameblade', 'Ember Ronin', 'Sun Blade'],
    ('samurai', 'lightning'): ['Raijin', 'Thunder Blade', 'Stormblade'],
    ('samurai', 'necromancy'): ['Shinigami', 'Bloodblade', 'Grave Ronin'],
    ('samurai', 'ice'): ['Frostblade', 'Winter Blade', 'Kori Kensei'],
    ('samurai', 'water'): ['Tideblade', 'Wave Ronin', 'Mizu Kensei'],
    ('samurai', 'assassin'): ['Shinobi', 'Ninja', 'Night Blade'],
    ('samurai', 'phantom'): ['Ghost Blade', 'Iaido Master', 'Mirror Blade'],
    ('samurai', 'scout'): ['Kaze', 'Wind Blade', 'Swift Ronin'],
    ('samurai', 'thief'): ['Yakuza', 'Bandit Ronin', 'Sly Blade'],
    ('samurai', 'wanderer'): ['Ronin', 'Wandering Blade', 'Drifter'],
    ('samurai', 'stalker'): ['Kyudoka', 'Archer Samurai', 'Bowblade'],
    ('samurai', 'druid'): ['Forest Blade', 'Kodama Guardian', 'Bamboo Ronin'],
    ('samurai', 'cursed'): ['Cursed Blade', 'Jujutsu Swordsman', 'Demon Blade'],
    ('berzerker', 'holy'): ['Zealot', 'Fanatic', 'War Priest'],
    ('berzerker', 'flame'): ['Inferno', 'Firebrand', 'Ashbringer'],
    ('berzerker', 'lightning'): ['Thunderborn', 'Storm Rager', 'Stormbreaker'],
    ('berzerker', 'necromancy'): ['Bloodreaver', 'Carnage Lord', 'Gorefiend'],
    ('berzerker', 'ice'): ['Frost Giant', 'Frostrager', 'Winter Wolf'],
    ('berzerker', 'water'): ['Leviathan', 'Kraken', 'Maelstrom'],
    ('berzerker', 'assassin'): ['Butcher', 'Throatcutter', 'Bloodhound'],
    ('berzerker', 'phantom'): ['Dervish', 'Bladestorm', 'Whirlwind'],
    ('berzerker', 'scout'): ['Raider', 'Marauder', 'Reaver'],
    ('berzerker', 'thief'): ['Pillager', 'Plunderer', 'Brigand'],
    ('berzerker', 'wanderer'): ['Barbarian', 'Nomad Chief', 'Wildling'],
    ('berzerker', 'stalker'): ['Headhunter', 'Savage Hunter', 'Warhawk'],
    ('berzerker', 'druid'): ['Werebeast', 'Primal', 'Beastheart'],
    ('berzerker', 'cursed'): ['Demon', 'Hellraiser', 'Possessed'],
    ('holy', 'flame'): ['Sunpriest', 'Phoenix', 'Solar Cleric'],
    ('holy', 'lightning'): ['Sky Judge', 'Thunder Priest', 'Divine Herald'],
    ('holy', 'necromancy'): ['Soul Shepherd', 'Twilight Priest', 'Lifebinder'],
    ('holy', 'ice'): ['Winter Saint', 'Frost Oracle', 'Crystal Priest'],
    ('holy', 'water'): ['Tide Priest', 'Rain Saint', 'Well Keeper'],
    ('holy', 'assassin'): ['Inquisitor', 'Holy Executioner', 'Blade of Faith'],
    ('holy', 'phantom'): ['Seraph', 'Angelblade', 'Spirit Saint'],
    ('holy', 'scout'): ['Herald', 'Pilgrim', 'Lightbringer'],
    ('holy', 'thief'): ['Relic Hunter', 'Pardoner', 'False Prophet'],
    ('holy', 'wanderer'): ['Friar', 'Mendicant', 'Missionary'],
    ('holy', 'stalker'): ['Witch Hunter', 'Vigilant', 'Arbalest of Faith'],
    ('holy', 'druid'): ['Hierophant', 'Lifewarden', 'Grove Priest'],
    ('holy', 'cursed'): ['Exorcist', 'Fallen Saint', 'Heretic'],
    ('flame', 'lightning'): ['Skyfire', 'Thunderflame', 'Blazestorm'],
    ('flame', 'necromancy'): ['Hellcaller', 'Pyre Lord', 'Ash Necromancer'],
    ('flame', 'ice'): ['Elementalist', 'Frostfire Mage', 'Equinox'],
    ('flame', 'water'): ['Steamweaver', 'Geyser Mage', 'Scald'],
    ('flame', 'assassin'): ['Smokeblade', 'Ember Shade', 'Cinder Assassin'],
    ('flame', 'phantom'): ["Will-o'-Wisp", 'Flicker', 'Phantom Flame'],
    ('flame', 'scout'): ['Firewalker', 'Wildfire', 'Ember Runner'],
    ('flame', 'thief'): ['Arsonist', 'Firebug', 'Ember Thief'],
    ('flame', 'wanderer'): ['Ashwalker', 'Hearthkeeper', 'Desert Nomad'],
    ('flame', 'stalker'): ['Firehawk', 'Ember Archer', 'Blazeshot'],
    ('flame', 'druid'): ['Volcanist', 'Magma Shaman', 'Ashgrove Druid'],
    ('flame', 'cursed'): ['Hellfire', 'Infernal', 'Soulburner'],
    ('lightning', 'necromancy'): ['Stormreaper', 'Galvanist', 'Thunder Lich'],
    ('lightning', 'ice'): ['Hailcaller', 'Stormfrost', 'Blizzard Mage'],
    ('lightning', 'water'): ['Tempest', 'Stormtide', 'Monsoon'],
    ('lightning', 'assassin'): ['Voltblade', 'Flash Assassin', 'Shock Shade'],
    ('lightning', 'phantom'): ['Arcflash', 'Stormdancer', 'Flash Phantom'],
    ('lightning', 'scout'): ['Stormrunner', 'Skyrider', 'Thunder Scout'],
    ('lightning', 'thief'): ['Quicksilver', 'Sparkfinger', 'Storm Bandit'],
    ('lightning', 'wanderer'): ['Storm Chaser', 'Skywalker', 'Thunder Nomad'],
    ('lightning', 'stalker'): ['Stormhawk', 'Thunderbow', 'Boltcaster'],
    ('lightning', 'druid'): ['Thunderbird', 'Storm Shaman', 'Weather Druid'],
    ('lightning', 'cursed'): ['Black Lightning', 'Hexstorm', 'Storm Demon'],
    ('necromancy', 'ice'): ['Lich', 'Winter Revenant', 'Frost Necromancer'],
    ('necromancy', 'water'): ['Drowned King', 'Abysscaller', 'Sea Wraith'],
    ('necromancy', 'assassin'): ['Reaper', 'Soulblade', 'Grim Shade'],
    ('necromancy', 'phantom'): ['Wraith', 'Specter', 'Banshee'],
    ('necromancy', 'scout'): ['Carrion Crow', 'Ghoul Rider', "Death's Courier"],
    ('necromancy', 'thief'): ['Grave Robber', 'Body Snatcher', 'Tomb Raider'],
    ('necromancy', 'wanderer'): ['Pale Pilgrim', 'Lost Soul', 'Undying Wanderer'],
    ('necromancy', 'stalker'): ['Deathbow', 'Bone Archer', 'Grim Hunter'],
    ('necromancy', 'druid'): ['Witch Doctor', 'Rot Druid', 'Blight Shaman'],
    ('necromancy', 'cursed'): ['Warlock', 'Hexmaster', 'Dread Sorcerer'],
    ('ice', 'water'): ['Glacier Mage', 'Floecaller', 'Polar Tide'],
    ('ice', 'assassin'): ['Icepick', 'Coldblood', 'Frost Shade'],
    ('ice', 'phantom'): ['Mirage', 'Snow Ghost', 'Ice Phantom'],
    ('ice', 'scout'): ['Frostrunner', 'Snowstrider', 'Tundra Scout'],
    ('ice', 'thief'): ['Frostfinger', 'Ice Cutter', 'Glacier Bandit'],
    ('ice', 'wanderer'): ['Tundrawalker', 'Northman', 'Winter Nomad'],
    ('ice', 'stalker'): ['Frost Archer', 'Icebow', 'Winter Hunter'],
    ('ice', 'druid'): ['Winter Druid', 'Frost Shaman', 'Tundra Sage'],
    ('ice', 'cursed'): ['Frost Demon', 'Hexfrost', 'Cold Curse'],
    ('water', 'assassin'): ['Riptide', 'Undertow', 'Drowner'],
    ('water', 'phantom'): ['Undine', 'Mist Dancer', 'Tide Phantom'],
    ('water', 'scout'): ['Mariner', 'Seafarer', 'Navigator'],
    ('water', 'thief'): ['Pirate', 'Corsair', 'Buccaneer'],
    ('water', 'wanderer'): ['Voyager', 'Sea Nomad', 'Islander'],
    ('water', 'stalker'): ['Harpooner', 'Tide Hunter', 'Whaler'],
    ('water', 'druid'): ['Marsh Druid', 'Rain Shaman', 'Bog Witch'],
    ('water', 'cursed'): ['Abyssal', 'Deep One', 'Tide Cultist'],
    ('assassin', 'phantom'): ['Shade', 'Nightshade', 'Ghost Assassin'],
    ('assassin', 'scout'): ['Spy', 'Infiltrator', 'Recon Blade'],
    ('assassin', 'thief'): ['Cutthroat', 'Knave', 'Guild Thief'],
    ('assassin', 'wanderer'): ['Bounty Hunter', 'Highwayman', 'Road Blade'],
    ('assassin', 'stalker'): ['Sniper', 'Deadeye', 'Silent Hunter'],
    ('assassin', 'druid'): ['Venomancer', 'Poisoner', 'Thorn Assassin'],
    ('assassin', 'cursed'): ['Hexblade', 'Black Hand', 'Cursed Dagger'],
    ('phantom', 'scout'): ['Windwalker', 'Blinkrunner', 'Ghost Runner'],
    ('phantom', 'thief'): ['Phantom Thief', 'Trickster', 'Gentleman Thief'],
    ('phantom', 'wanderer'): ['Vagabond', 'Poltergeist', 'Ghost Walker'],
    ('phantom', 'stalker'): ['Ghost Archer', 'Phantom Hunter', 'Spectral Bow'],
    ('phantom', 'druid'): ['Fey Blade', 'Sylph', 'Spirit Druid'],
    ('phantom', 'cursed'): ['Doppelganger', 'Hollow', 'Cursed Specter'],
    ('scout', 'thief'): ['Prowler', 'Burglar', 'Scoundrel'],
    ('scout', 'wanderer'): ['Explorer', 'Pathfinder', 'Trailblazer'],
    ('scout', 'stalker'): ['Ranger', 'Huntsman', 'Tracker'],
    ('scout', 'druid'): ['Wildrunner', 'Greenwarden', 'Woodland Scout'],
    ('scout', 'cursed'): ['Omen', 'Crowseer', 'Shadow Scout'],
    ('thief', 'wanderer'): ['Swindler', 'Vagrant', 'Peddler'],
    ('thief', 'stalker'): ['Outlaw', 'Poacher', 'Bandit Archer'],
    ('thief', 'druid'): ['Fox', 'Magpie', 'Greenwood Outlaw'],
    ('thief', 'cursed'): ['Soul Thief', 'Jinx', 'Hex Thief'],
    ('wanderer', 'stalker'): ['Frontiersman', 'Trapper', 'Woodsman'],
    ('wanderer', 'druid'): ['Hermit', 'Beastwalker', 'Hedge Druid'],
    ('wanderer', 'cursed'): ['Exile', 'Outcast', 'Cursed Pilgrim'],
    ('stalker', 'druid'): ['Wild Hunter', 'Thorn Archer', 'Sylvan Archer'],
    ('stalker', 'cursed'): ['Hexbow', 'Doom Hunter', 'Cursed Marksman'],
    ('druid', 'cursed'): ['Witch', 'Dark Druid', 'Blighted Shaman'],
}

if __name__ == '__main__':
    import itertools, json, collections
    pairs = list(itertools.combinations(ARCHETYPES, 2))
    missing = [p for p in pairs if p not in NAMES]
    extra = [p for p in NAMES if p not in pairs]
    dupes = [n for n, c in collections.Counter(n for v in NAMES.values() for n in v).items() if c > 1]
    print(len(pairs), 'pairs; missing', missing, 'extra', extra, 'duplicate names', dupes)

# The chosen names: per first archetype, one entry per pair in NAMES order (1-3 = option A-C, or a custom name).
# Groups not chosen yet show "<first> / <second>" in game until they are filled in.
PICKS = {
    'knight': [3, 2, 3, 1, 2, 1, 1, 2, 3, 3, 2, 1, 1, 3, 2, 3],
    'samurai': [1, 3, 3, 1, 1, "Kuraokami's Blade", 1, 1, 3, 1, 2, 1, 3, 1, 3],
    'berzerker': [1, 1, 1, 3, 2, 3, 1, 3, 2, 2, 3, 3, 2, 3],
    'holy': [1, 2, 2, 3, 1, 2, 1, 2, 3, 3, 1, 2, 3],
    'flame': [3, 3, 3, 3, 1, 1, 2, 3, 3, 3, 3, 3],
    'lightning': [1, 3, 2, 2, 2, 3, 3, 1, 1, 2, 1],
    'necromancy': [2, 2, 1, 1, 1, 1, 1, 2, 3, 3],
    'ice': [3, 2, 3, 1, 3, 3, 2, 1, 2],
    'water': [1, 2, 2, 2, 2, 2, 2, 1],
    'assassin': ['Reaper', 2, 1, 1, 2, 2, 2],
    'scout': [3, 2, 2, 3, 3],
    'stalker': [3, 3],
    'druid': [2],
}


def chosen():
    """{(first, second): name} for every pair that has been picked."""
    out = {}
    for first, picks in PICKS.items():
        pairs = [p for p in NAMES if p[0] == first]
        assert len(picks) == len(pairs), (first, len(picks), len(pairs))
        for pair, pick in zip(pairs, picks):
            out[pair] = pick if isinstance(pick, str) else NAMES[pair][pick - 1]
    return out
