#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Oct 05 10:03:52 BST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=MakeUp-UltraFast-9.5g.zip
enableShaders=false
